<?php

namespace Test\Ease\ui;

use Ease\ui\BooleanLED;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-12-23 at 02:03:16.
 */
class BooleanLEDTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var BooleanLED
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BooleanLED();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Ease\ui\BooleanLED::colorNameToHex
     */
    public function testColorNameToHex()
    {
        $this->assertEquals('#556B2F',  BooleanLED::colorNameToHex('darkolivegreen'));
    }

    /**
     * @covers Ease\ui\BooleanLED::getColorCode
     */
    public function testGetColorCode()
    {
        $this->assertEquals('#c8c8ff', $this->object->getColorCode('blue',true));
        $this->assertEquals('#0000af', $this->object->getColorCode('blue',false));
    }

    /**
     * @covers Ease\ui\BooleanLED::adjustBrightness
     */
    public function testAdjustBrightness()
    {
        $this->assertEquals('#ffff7b', BooleanLED::adjustBrightness('#ffbf00', 123));
    }
}
