<?php

declare(strict_types=1);

/**
 * This file is part of the Ease TWBootstrap4 Widgets package
 *
 * https://github.com/VitexSoftware/php-ease-twbootstrap4-widgets
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\Ease\ui;

use Ease\TWB\Widgets\MainPageMenu;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-12-20 at 17:21:58.
 */
class MainPageMenuTest extends \PHPUnit\Framework\TestCase
{
    protected MainPageMenu $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new MainPageMenu();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \Ease\ui\MainPageMenu::addMenuItem
     */
    public function testAddMenuItem(): void
    {
        $this->object->addMenuItem('https://www.vitexsoftware.cz/img/ease-framework-logo.png', 'Ease Framework', 'https://www.vitexsoftware.cz/ease.php');
    }

    /**
     * @covers \Ease\ui\MainPageMenu::finalize
     */
    public function testFinalize(): void
    {
        $this->object->finalize();
    }
}
