<?php

declare(strict_types=1);

/**
 * This file is part of the Ease TWBootstrap4 Widgets package
 *
 * https://github.com/VitexSoftware/php-ease-twbootstrap4-widgets
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\Ease\ui;

use Ease\TWB\Widgets\SemaforLight;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-12-23 at 02:03:16.
 */
class SemaforLEDTest extends \PHPUnit\Framework\TestCase
{
    protected SemaforLight $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new SemaforLight();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \Ease\ui\SemaforLight::colorNameToHex
     */
    public function testColorNameToHex(): void
    {
        $this->assertEquals(
            '#556B2F',
            SemaforLight::colorNameToHex('darkolivegreen'),
        );
    }

    /**
     * @covers \Ease\ui\SemaforLight::getColorCode
     */
    public function testGetColorCode(): void
    {
        $this->assertEquals('#f0ad4e', $this->object->getColorCode('warning'));
        $this->assertEquals('#0000FF', $this->object->getColorCode('blue'));
    }

    /**
     * @covers \Ease\ui\SemaforLight::adjustBrightness
     */
    public function testAdjustBrightness(): void
    {
        $this->assertEquals(
            '#ffff7b',
            SemaforLight::adjustBrightness('#ffbf00', 123),
        );
    }
}
